# Generated by Django 4.2.30 on 2026-09-09 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('participants', '0001_initial'),
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcompetitor',
            name='competitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_results', to='participants.competitor'),
        ),
        migrations.AddField(
            model_name='eventcompetitor',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventcompetitor',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.statuseventcompetitor'),
        ),
        migrations.AddField(
            model_name='event',
            name='competition_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.competitionstage'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_result_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.eventresulttype'),
        ),
        migrations.AddField(
            model_name='event',
            name='rank_direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.rankdirection'),
        ),
        migrations.AddField(
            model_name='competitionstage',
            name='competition_edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='competitions.competitionedition'),
        ),
        migrations.AddField(
            model_name='competitionenabledcategory',
            name='competition_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enabled_in_editions', to='events.competitioncategory'),
        ),
        migrations.AddField(
            model_name='competitionenabledcategory',
            name='competition_edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enabled_categories', to='competitions.competitionedition'),
        ),
        migrations.AlterUniqueTogether(
            name='eventcompetitor',
            unique_together={('competitor', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('competition_stage', 'event_number')},
        ),
        migrations.AlterUniqueTogether(
            name='competitionenabledcategory',
            unique_together={('competition_edition', 'competition_category')},
        ),
    ]
