# Generated by Django 4.2.30 on 2026-09-10 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_statuscompetition_and_more'),
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnabledCompetitionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['competition_category'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='competitionenabledcategory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='competitionenabledcategory',
            name='competition_category',
        ),
        migrations.RemoveField(
            model_name='competitionenabledcategory',
            name='competition_edition',
        ),
        migrations.RemoveField(
            model_name='competitionstage',
            name='competition_edition',
        ),
        migrations.AddField(
            model_name='competitionstage',
            name='competition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='competitions.competition'),
            preserve_default=False,
        ),
    ]
