# Generated by Django 4.2.30 on 2026-09-10 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_remove_competitor_competition_edition_and_more'),
        ('events', '0003_enabledcompetitioncategory_and_more'),
        ('competitions', '0003_delete_competitionedition_competition_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompetitionEnabledCategory',
        ),
        migrations.AddField(
            model_name='enabledcompetitioncategory',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enabled_categories', to='competitions.competition'),
        ),
        migrations.AddField(
            model_name='enabledcompetitioncategory',
            name='competition_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enabled_in_editions', to='events.competitioncategory'),
        ),
        migrations.AlterUniqueTogether(
            name='enabledcompetitioncategory',
            unique_together={('competition', 'competition_category')},
        ),
    ]
