# Generated by Django 4.2.30 on 2026-09-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_delete_competitionenabledcategory_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enabledcompetitioncategory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='eventcompetitor',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_ascending',
            field=models.BooleanField(default=False, help_text='Indica si el resultado se ordena de menor a mayor.'),
        ),
        migrations.AddField(
            model_name='event',
            name='workout',
            field=models.TextField(default='hola'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='enabledcompetitioncategory',
            constraint=models.UniqueConstraint(fields=('competition', 'competition_category'), name='unique_enabled_category_per_competition'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('competition_stage', 'event_number'), name='unique_event_number_per_stage'),
        ),
        migrations.AddConstraint(
            model_name='eventcompetitor',
            constraint=models.UniqueConstraint(fields=('competitor', 'event'), name='unique_competitor_per_event'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_result_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='rank_direction',
        ),
        migrations.RemoveField(
            model_name='eventcompetitor',
            name='status',
        ),
        migrations.DeleteModel(
            name='EventResultType',
        ),
        migrations.DeleteModel(
            name='RankDirection',
        ),
        migrations.DeleteModel(
            name='StatusEventCompetitor',
        ),
    ]
