# Generated by Django 4.2.30 on 2026-09-09 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField()),
                ('competition_edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_rules', to='competitions.competitionedition')),
            ],
            options={
                'ordering': ['competition_edition', 'position'],
                'unique_together': {('competition_edition', 'position')},
            },
        ),
    ]
