# Generated by Django 4.2.30 on 2026-09-10 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_statuscompetition_and_more'),
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoringrule',
            options={'ordering': ['competition', 'position']},
        ),
        migrations.AlterUniqueTogether(
            name='scoringrule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='scoringrule',
            name='competition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scoring_rules', to='competitions.competition'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='scoringrule',
            unique_together={('competition', 'position')},
        ),
        migrations.RemoveField(
            model_name='scoringrule',
            name='competition_edition',
        ),
    ]
