# Generated by Django 4.2.30 on 2026-09-10 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_remove_competitor_competition_edition_and_more'),
        ('scoring', '0002_alter_scoringrule_options_and_more'),
        ('competitions', '0002_statuscompetition_and_more'),
        ('events', '0003_enabledcompetitioncategory_and_more'),
        ('users', '0002_competitionadmin_remove_user_role_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompetitionEdition',
        ),
        migrations.AddField(
            model_name='competition',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='competitions', to='competitions.statuscompetition'),
            preserve_default=False,
        ),
    ]
