# Generated by Django 4.2.30 on 2026-09-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_delete_competitionedition_competition_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='finalist_slots',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
