# Generated by Django 4.2.30 on 2026-09-10 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_enabledcompetitioncategory_and_more'),
        ('competitions', '0002_statuscompetition_and_more'),
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitor',
            name='competition_edition',
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='competition_enabled_category',
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='person',
        ),
        migrations.RemoveField(
            model_name='team',
            name='competition_edition',
        ),
        migrations.RemoveField(
            model_name='team',
            name='competition_enabled_category',
        ),
        migrations.AddField(
            model_name='competitor',
            name='competition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='competitions.competition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competitor',
            name='enabled_competition_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='competitors', to='events.enabledcompetitioncategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='competition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='competitions.competition'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='Athletes/')),
                ('affiliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.affiliation')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='competitor',
            name='athlete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='participants.athlete'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='athlete',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='participants.athlete'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('team', 'athlete')},
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='person',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
