# Generated by Django 4.2.30 on 2026-09-21 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_remove_competitor_competition_edition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='competition',
        ),
    ]
