# Generated by Django 4.2.30 on 2026-10-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_remove_team_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='Athletes/'),
        ),
    ]
